[build]
builder = "NIXPACKS"

[deploy]
startCommand = "java -jar target/assignment-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
SPRING_PROFILES_ACTIVE = "prod"